### ISSUE TITLE
feature request: file_rec and defx actions

### ISSUE THREAD

**Issue by petobens** [rafi/vim-denite-z#1]
I was wondering if you could add two features:
i) a file_rec action that instead of narrowing candidates by `narrow` action can recursively list all files in the directory
ii) add defx integration (i.e allow to callo denite-z source from a defx buffer and then cd to selected candidate). As in https://github.com/kmnk/denite-dirmark/pull/3/files#diff-0c1347fbefad2bb2e7195e9092f274bcR63

Thank you!

**Comment by petobens** [comment]
I ended up implementing it directly with `denite#custom#action`.

**Comment by rafi** [comment]
Hi @petobens - can you share your integrations?

**Comment by petobens** [comment]
Sure. See here: https://github.com/petobens/dotfiles/blob/c8309b987036f1c3a62a0da83d4d32919e19bcb0/vim/init.vim#L1771-L1788
